# general settings
name: OSRT_x2_fisheye_aug
model_type: ODISRModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: ODISR_train
    type: ERPPairedImageDataset
    dataroot_gt: datasets/lau_dataset_clean/odisr/training/HR_sub
    dataroot_lq: datasets/lau_dataset_clean/odisr/training/LR_fisheye/X2_sub
    ext_dataroot_gt: [datasets/DF2K-ODI/HR]
    ext_dataroot_lq: [datasets/DF2K-ODI/LR/X2]
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb
    enlarge_scale: [6, 1]

    gt_size: 128
    use_hflip: true
    use_rot: false
    return_top: true
    force_resize: true
    gt_h: 1024
    gt_w: 2048
    condition_type: cos_latitude
    sub_image: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1

  val:
    name: ODISR_val
    type: ERPPairedImageDataset
    dataroot_gt: datasets/lau_dataset_clean/odisr/validation/HR
    dataroot_lq: datasets/lau_dataset_clean/odisr/validation/LR_fisheye/X2
    io_backend:
      type: disk

    condition_type: cos_latitude

# network structures
network_g:
  type: OSRT
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 156
  c_dim: 156
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  condition_dim: 1
  vit_condition: [6, 6, 6, 6, 6, 6]
  vit_condition_type: '3conv'
  window_condition: true
  dcn_condition: [1, 1, 1, 1, 1, 1, 1]
  dcn_condition_type: '2conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings (slurm only)
dist_params:
  backend: nccl
  port: 29500